import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout";
import { Rubik, Syne } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});
const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${syne.variable} antialiased debug-screens`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
